### ISSUE TITLE
Port collisions when running magic-create via NPX 

### ISSUE THREAD

**Issue by aldonline** [decoupled/magic#12]
* v0.0.22
* This error is intermittent. Most likely a race condition. Happens when running via NPX
* It looks like the SPA dev server is trying to start twice

```
npx @decoupled/magic create my-project \
  --autostart \
  --spa \
  --electron \
  --electron_title="My Electron App" \
  --lambda
creating magic project with the following modules:
 - electron
 - spa
 - lambda
installing dependencies (this can take a while)... done
compiling magic project... done
Starting SPA dev server...
Starting Dev Server...
  lambda server ready on port 5555
  spa server ready on port 4444
Dev Server listening on http://localhost:3333
⠋ Building... / 200 OK
⠙ Building... /2w3i7n0iin1xwr1c3ityy61c6dgskujc2kz3s.1270e9d0.js
200 OK
⠹ Building klblhczsmzimwb1ydccuh6ew1rmlhgkaqabrgdue.main.js...
✨  Built in 288ms.
Starting Dev Server...
  lambda server ready on port 4343
⠋ Building...g at http://localhost:5454
✨  Built in 746ms.
  frontend server ready on port 5454
Dev Server listening on http://localhost:5675
Starting Electron dev server...... done
Starting SPA dev server...
Starting Dev Server...
  lambda server ready on port 5555
dyld: Library not loaded: @rpath/Squirrel.framework/Squirrel
  Referenced from: /Users/aldo/.npm/_npx/919/lib/node_modules/@decoupled/magic/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework
  Reason: image not found
events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::5555
    at Server.setupListenHandle [as _listen2] (net.js:1226:14)
    at listenInCluster (net.js:1274:12)
    at Server.listen (net.js:1362:7)
    at Function.listen (/Users/aldo/.npm/_npx/919/lib/node_modules/@decoupled/magic/node_modules/express/lib/application.js:618:24)
    at /Users/aldo/.npm/_npx/919/lib/node_modules/@decoupled/magic/cli.js:2263:23
    at new Promise (<anonymous>)
    at Object.<anonymous> (/Users/aldo/.npm/_npx/919/lib/node_modules/@decoupled/magic/cli.js:2261:18)
    at Generator.next (<anonymous>)
    at /Users/aldo/.npm/_npx/919/lib/node_modules/@decoupled/magic/cli.js:2162:67
    at new Promise (<anonymous>)
Emitted 'error' event at:
    at emitErrorNT (net.js:1253:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:9)
```

**Comment by aldonline** [comment]
fixed in [v0.0.23](https://dev.decoupled.com/version)
